# -*- coding: utf-8 -*-
from . import account_move
from . import delivery_carrier
from . import delivery_price_rule
from . import loyalty_program
from . import loyalty_reward
from . import loyalty_rule
from . import mail_message
from . import mv_compute_discount
from . import mv_compute_discount_line
from . import mv_discount
from . import mv_discount_line
from . import mv_discount_partner
from . import mv_discount_partner_history
from . import mv_discount_warranty
from . import mv_promote_discount_line
from . import mv_white_place_discount_line
from . import product_attribute
from . import product_template
from . import res_partner
from . import sale_make_invoice_advance
from . import sale_order
from . import sale_order_line
